### ISSUE TITLE
WordPress complains this plug-in is out of date

### ISSUE THREAD

**Issue by bidmead** [tfrommen/bring-back-the-get-shortlink-button#1]
It almost certainly doesn't need an update but WordPress is looking at the date of the last version change and warning that the plugin is being neglected by the developer. WordPress is not canny enough to grok that five years ago the developer, seeing far into the future, was able to create a plug-in that continues to work flawlessly.

Nevertheless, I'm wondering if Thorsten might be able to find time just to change the version number or whatever it might take for WordPress to be appeased.

– 
Chris

**Comment by tfrommen** [comment]
Done.

- https://github.com/tfrommen/bring-back-the-get-shortlink-button/releases/tag/v1.2.0
- https://wordpress.org/plugins/bring-back-the-get-shortlink-button/

👍
